spring.thymeleaf.cache: false
spring.devtools.restart.enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#spring.devtools.restart.additional-paths: src/main/resources
##spring.dev
#
#server:
#  port: 8888
#spring:
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      exclude: application.yml
